### ISSUE TITLE
sprint-backlog

### ISSUE THREAD

**Issue by DaoDucKhiem** [DaoDucKhiem/nhom-5#2]
Sprint 1: thời hạn từ 25/2 đến 3/3 (tuần 4).
1. Học ngôn ngữ PHP, tìm hiểu Framework và Laravel.
2. Học cơ sở dữ liệu (MySQL)

**Comment by DucLoc1999** [comment]
Tôi học xong phần PHP cơ bản rồi cơ mà để sử dụng Laravel còn cần học gì không?

**Comment by DucLoc1999** [comment]
1. Học xong php cơ bản, đang làm quen với Laravel.
2. đang học mySQL.

**Comment by DucLoc1999** [comment]
close
