### ISSUE TITLE
Là một quản trị viên, tôi muốn thêm các mặt hàng hay các loại sản phẩm để để có thể cung cấp thêm sản phẩm cho người mua hàng

### ISSUE THREAD

**Issue by blackpanter99** [DaoDucKhiem/nhom-5#22]
- [ ] Xây dựng giao diện cho việc thêm sản phẩm mới hay thêm loại sản phẩm mới.
- [ ] Kiểm thử lỗi về bố cục giao diện trên các nền tảng mobile hay là trên máy tính.
- [ ] Tìm hiểu về cách thức di chuyển file ảnh từ thư mục này sang thư mục khác trong framework laravel.
- [ ] Cảnh báo lỗi nếu nhập sai về cú pháp , chuỗi rỗng , chuỗi quá dài.
- [ ] Lấy dữ liệu từ các input và kiểm tra về tính đúng đắn về dữ liệu. 
- [ ] Thêm các dữ liệu đã nhập sau khi đã được kiểm thử vào cơ sở dữ liệu để cập nhập sản phẩm hay mặt hàng.
- [ ]  Kiểm thử sau khi sản phẩm đã được cập nhật lên trang web xem có đúng như những gì mình mong muốn.
- [ ] Soát lại mã nguồn đảm bảo không bị lỗi chính tả và lỗi về form.
- [ ]  Kiểm tra tên hàm, tên biến cho phù hợp.

**Comment by blackpanter99** [comment]
[] Xây dựng giao diện cho việc thêm sản phẩm mới hay thêm loại sản phẩm mới
[] Kiểm thử lỗi về bố cục giao diện trên các nền tảng mobile hay là trên máy tính
[] Tìm hiểu về cách thức di chuyển file ảnh từ thư mục này sang thư mục khác trong framework laravel
[] Xử lý về các lỗi khi nhập vào ô input như quá dài , không đúng cú pháp ....
[] Lấy dữ liệu từ các input và kiểm tra về tính đúng đắn về dữ liệu 
[] Thêm các dữ liệu đã nhập sau khi đã được kiểm thử vào database để cập nhập sản phẩm hay mặt hàng
[] Kiểm thử sau khi sản phẩm đã được cập nhật lên trang web xem có đúng như những gì mình mong muốn

**Comment by DaoDucKhiem** [comment]
đã hoàn thành ở issues tạo ra một trang web dành riêng cho quản trị viên bởi Nguyễn Cảnh Hoàng
